### ISSUE TITLE
Please give credit in the README

### ISSUE THREAD

**Issue by Explosion-Scratch** [mmRoshani/mmRoshani.github.io#1]
This repo was clearly forked from https://GitHub.com/explosion-scratch/blog (see https://explosion-scratch.github.io/blog ) and I worked really hard to create it all myself. I'm happy for you to fork it and add your own posts but please credit me in the README or project description and on the site itself. Thanks

- Explosion-Scratch

**Comment by Explosion-Scratch** [comment]
Also your method of publishing this site is awful, you should fork the original repo and then set up a GitHub action to publish for you instead of just using wget or curl to download the entire site.

**Comment by mmRoshani** [comment]
thanks for the note, yes I mentioned the main repository at the end of each post and I am not going to use this repository so I built it and put the dist folder in the root of the project to see the demo in RTL mode.
Thank you for your work, if I choose this project for my blog be sure that I will mention you as the main author & creator.

**Comment by Explosion-Scratch** [comment]
> thanks for the note, yes I mentioned the main repository at the end of each post and I am not going to use this repository so I built it and put the dist folder in the root of the project to see the demo in RTL mode. Thank you for your work, if I choose this project for my blog be sure that I will mention you as the main author & creator.

I don't see any attribution anywhere in the repo or the site still. Please provide attribution even if you don't plan to use this as your blog.
